### PR TITLE
Use increment-less for-loop instead of while

### PR DESCRIPTION
**Pull request by pips-**
For conciseness, readability and counter logic, a for-loop may be better
than a while.

I tried over-think how we may use time(2) logic, recording start time and/or end time, computing the remaining time, sleep(3)ing for this period, saving time state before and after suspend, etc, in order to have a better while logic. 

But finally, I think the sleep(3) for 1 second is really fine, so this patch is more aesthetic and more related to the logic of a for-loop counter.

### CODE REVIEW

**Comment by pickfire** [comment]
@pips- Thanks a lot for taking my words seriously but then I don't see how is this better than not applying the patch, therefore I don't plan on merging this patch. If by any chance I am wrong, please prove me wrong.

**Comment by pips-** [comment]
No problem. :)

I agree the change for a for-loop is mainly aesthetic. The loop, before I changed the handling of sig USR2 was a for-loop, so I thought you may prefer this.

But beside this consideration, the for-loop may be more related to a counter logic than a while, and this loop is a (time)counter one, so this may be more logical.

But feel free to accept or not, in the end, this isn't a major issue . :)

Aside the while/for patch, may you have a look about moving the timecount increment one line up, just before the sleep please?

**Comment by pickfire** [comment]
@pips- Yeah, I saw that, I think that is also a reason why I don't accept the patch, I just forgot to say so.

Actually, I like a for-loop but after changing it looks uglier than being while-loop so I don't want to change.

What I think is that if people just send signal USR2 simultaneously, this would speed up a few seconds right? I think people wouldn't want that.

**Comment by pips-** [comment]
You are pointing something I reached when thinking about changing the one second sleep.

Imagine, or try, to change the call to `sleep` from 1 second to 10 seconds, and accordingly change the timecount increment to something like `timecount += 10`.

This will works as it has always worked, just the increment is superior but the sleep is longer.

But if spt catch a signal during the 10 seconds sleep (say at the 5th second),  the handler will be executed, then sleep will return, and we will increment `timecount` by 10, and newloop.

We have just sleep 5 seconds, but we have increment `timecount` by 10, so we "lost" 5 seconds in the timer!

Return to normal situation, we use a sleep for 1 second only : It can happen that a signal is catch only at 0.5 seconds, and the we will increment `timecount` by 1 "second", even if the sleep was shorter.

`sleep(3)` can return the number of second left to sleep, if the call was interrupted by a signal handler, but as we are below the second, I think it will return 0 or 1, which will not be accurate.

The other solution may be using computing a ending timestamp for the current counter, sleeping for a number of seconds equals to `ending_timestamp - time()`, but in the case of timer suspending on SIGUSR2, we need to save the remaining time, wait for a new signal to toggle suspend, and then compute the new due date with the remaining time.

This may be more complicated, but will be more accurate.

As spt is not designed for NASA and space rockets, I thought this would not be a major issue to leak 0.1 to 0.9 second on each signals, for a 25 minutes timer. :)

But if you are really concerned about this, I can try to come with another design for the main loop, that will handle all this case. :)

**Comment by pickfire** [comment]
Haha, space rockets.

So this doesn't make it more accurate, it's just waste lesser time. I think I can accept this patch not together with the for loop. Maybe after the other issue.

**Pull request closed without merging**
